apiVersion: v1
kind: PersistentVolume
metadata:
  name: cchw2redis
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/cchw2redis"
