---
  kind: Service
  apiVersion: v1
  metadata:
    name: url-shortener-svc
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 1500
        targetPort: 8001
    selector:
      app: url-shortener