---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: marmary2001/url-shortener:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: url-shortener-service-configs
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: url-shortener-service-configs
          configMap:
            name: url-shortener-service-configs