---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cchw2redis
  labels:
    app: cchw2redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cchw2redis
  template:
    metadata:
      labels:
        app: cchw2redis
    spec:
      containers:
        - name: cchw2redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379

          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cchw2redis-pvc